Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -31,18 +31,102 @@ executors:
       psql_version:
         type: string
         default: "9.6.16"
+
 jobs:
-  build:
+  ruby-install-deps:
     docker:
       - image: cimg/base:stable
+    parameters:
+      app-dir:
+        default: .
+        description: >
+          Path to the directory containing your Gemfile file. Not needed if Gemfile
+          lives in the root.
+        type: string
+      bundler-version:
+        default: ''
+        description: >
+          Configure which version of bundler to install and utilize. By default, it
+          gets the bundler version from Gemfile.lock, but if it is not working use
+          this to override.
+        type: string
+      key:
+        default: gems-v1
+        description: The cache key to use. The key is immutable.
+        type: string
+      path:
+        default: ./vendor/bundle
+        description: >
+          Installation path. By default, it will run bundle with `--deployment` flag
+          and installs gems to the vendor/bundle directory.
+        type: string
+      with-cache:
+        default: true
+        description: Enable automatic caching of your gemfile dependencies for increased speed.
+        type: boolean
     steps:
       - checkout
+      - when:
+          condition: <<parameters.with-cache>>
+          steps:
+            - restore_cache:
+                keys:
+                  - >-
+                    << parameters.key >>-{{ checksum
+                    "<<parameters.app-dir>>/Gemfile.lock"  }}-{{ .Branch }}
+                  - >-
+                    << parameters.key >>-{{ checksum
+                    "<<parameters.app-dir>>/Gemfile.lock"  }}
+                  - << parameters.key >>
       - run:
-          name: Install Dependancies
-          command: bundle install
-      - node/install-packages:
-          pkg-manager: yarn
-          cache-key: "yarn.lock"
+          command: |
+            if test -f "Gemfile.lock"; then
+              APP_BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")
+              if [ -z "$APP_BUNDLER_VERSION" ]; then
+                echo "Could not find bundler version from Gemfile.lock. Please use bundler-version parameter"
+              else
+                echo "Gemfile.lock is bundled with bundler version $APP_BUNDLER_VERSION"
+              fi
+            fi
+
+            if ! [ -z <<parameters.bundler-version>> ]; then
+              echo "Found bundler-version parameter to override"
+              APP_BUNDLER_VERSION=<<parameters.bundler-version>>
+            fi
+
+            if ! echo $(bundle version)  | grep -q $APP_BUNDLER_VERSION; then
+              echo "Installing bundler $APP_BUNDLER_VERSION"
+              gem install bundler:$APP_BUNDLER_VERSION
+            else
+              echo "bundler $APP_BUNDLER_VERSION is already installed."
+            fi
+
+            if bundle config set > /dev/null 2>&1; then
+              if [ "<< parameters.path >>" == "./vendor/bundle" ]; then
+                bundle config deployment 'true'
+              fi
+              bundle config path << parameters.path >>
+            else
+              if [ "<< parameters.path >>" == "./vendor/bundle" ]; then
+                bundle config set deployment 'true'
+              fi
+              bundle config set path << parameters.path >>
+            fi
+
+            bundle check || bundle install
+          name: >-
+            Bundle Install <<^parameters.with-cache>>(No
+            Cache)<</parameters.with-cache>>
+          working_directory: <<parameters.app-dir>>
+      - when:
+          condition: <<parameters.with-cache>>
+          steps:
+            - save_cache:
+                key: >-
+                  << parameters.key >>-{{ checksum
+                  "<<parameters.app-dir>>/Gemfile.lock"  }}-{{ .Branch }}
+                paths:
+                  - <<parameters.app-dir>>/<< parameters.path >>
 
   test:
     docker:
@@ -63,12 +147,6 @@ jobs:
     steps:
       - checkout
       - run:
-          name: Install Dependancies
-          command: bundle install
-      - node/install-packages:
-          pkg-manager: yarn
-          cache-key: "yarn.lock"
-      - run:
           name: DB Locate
           command: dockerize -wait tcp://localhost:5432 -timeout 1m
       - run:
@@ -86,5 +164,8 @@ jobs:
 workflows:
   workflow:
     jobs:
-      - build
+      - ruby-install-deps
       - test
+
+
+
